language: go

go:
  - 1.x

env:
  - GO111MODULE=on

install: true

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me
notifications:
  email: false

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.22.2

script:
  - go test -v ./...
  - golangci-lint run
